export const LOG_USER = "LOG_USER";
export const ADD_SUBSCRIPTION = "ADD_SUBSCRIPTION";
export const REMOVE_SUBSCRIPTION = "REMOVE_SUBSCRIPTION";
export const UPDATE_SUBSCRIPTION = "UPDATE_SUBSCRIPTION";
export const UPDATE_CRYPTO = "UPDATE_CRYPTO";